FROM php:7.4-apache

COPY apache/host.conf /etc/apache2/sites-available/000-default.conf
COPY apache/start-apache /usr/local/bin
RUN a2enmod rewrite

RUN docker-php-ext-install mysqli

# Copy application source
COPY . /var/www/
RUN rm -r /var/www/apache
RUN rm -r /var/www/database
RUN chown -R www-data:www-data /var/www

CMD ["start-apache"]
